<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class CarDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $carData = [
            ['brand' => 'Toyota', 'model' => 'Vios', 'type' => 'Sedan'],
            ['brand' => 'Toyota', 'model' => 'Fortuner', 'type' => 'SUV'],
            ['brand' => 'Toyota', 'model' => 'Innova', 'type' => 'MPV'],
            ['brand' => 'Toyota', 'model' => 'Camry', 'type' => 'Sedan'],
            ['brand' => 'Toyota', 'model' => 'Hiace', 'type' => 'Van'],
            ['brand' => 'Toyota', 'model' => 'Hilux', 'type' => 'Pickup Truck'],
            ['brand' => 'Toyota', 'model' => 'Corolla Altis', 'type' => 'Sedan'],
            ['brand' => 'Toyota', 'model' => 'Land Cruiser', 'type' => 'SUV'],
            ['brand' => 'Toyota', 'model' => 'Wigo', 'type' => 'Hatchback'],
            ['brand' => 'Toyota', 'model' => 'Hilux Conquest', 'type' => 'Pickup Truck'],
            ['brand' => 'Toyota', 'model' => 'Rav4', 'type' => 'SUV'],
            ['brand' => 'Toyota', 'model' => 'FJ Cruiser', 'type' => 'SUV'],
            ['brand' => 'Toyota', 'model' => 'Supra', 'type' => 'Sports Car'],
            ['brand' => 'Toyota', 'model' => 'Camry', 'type' => 'Sedan'],
            ['brand' => 'Toyota', 'model' => 'Corolla', 'type' => 'Sedan'],
            ['brand' => 'Toyota', 'model' => 'Yaris', 'type' => 'Hatchback'],
            ['brand' => 'Toyota', 'model' => 'RAV4', 'type' => 'SUV'],
            ['brand' => 'Toyota', 'model' => 'Highlander', 'type' => 'SUV'],
            ['brand' => 'Toyota', 'model' => 'Land Cruiser', 'type' => 'SUV'],
            ['brand' => 'Toyota', 'model' => 'Tacoma', 'type' => 'Pickup Truck'],
            ['brand' => 'Toyota', 'model' => 'Tundra', 'type' => 'Pickup Truck'],
            ['brand' => 'Honda', 'model' => 'Civic', 'type' => 'Sedan'],
            ['brand' => 'Honda', 'model' => 'CR-V', 'type' => 'SUV'],
            ['brand' => 'Honda', 'model' => 'Jazz', 'type' => 'Hatchback'],
            ['brand' => 'Honda', 'model' => 'Accord', 'type' => 'Sedan'],
            ['brand' => 'Honda', 'model' => 'HR-V', 'type' => 'SUV'],
            ['brand' => 'Honda', 'model' => 'City', 'type' => 'Sedan'],
            ['brand' => 'Honda', 'model' => 'Brio', 'type' => 'Hatchback'],
            ['brand' => 'Honda', 'model' => 'BR-V', 'type' => 'SUV'],
            ['brand' => 'Honda', 'model' => 'Odyssey', 'type' => 'MPV'],
            ['brand' => 'Honda', 'model' => 'BR-V', 'type' => 'SUV'],
            ['brand' => 'Honda', 'model' => 'City', 'type' => 'Sedan'],
            ['brand' => 'Honda', 'model' => 'HR-V RS', 'type' => 'SUV'],
            ['brand' => 'Honda', 'model' => 'Ridgeline', 'type' => 'Pickup Truck'],
            ['brand' => 'Mitsubishi', 'model' => 'Mirage', 'type' => 'Hatchback'],
            ['brand' => 'Mitsubishi', 'model' => 'Montero Sport', 'type' => 'SUV'],
            ['brand' => 'Mitsubishi', 'model' => 'L300', 'type' => 'Van'],
            ['brand' => 'Mitsubishi', 'model' => 'Xpander', 'type' => 'MPV'],
            ['brand' => 'Mitsubishi', 'model' => 'Strada', 'type' => 'Pickup Truck'],
            ['brand' => 'Mitsubishi', 'model' => 'Outlander', 'type' => 'SUV'],
            ['brand' => 'Mitsubishi', 'model' => 'Pajero', 'type' => 'SUV'],
            ['brand' => 'Mitsubishi', 'model' => 'Mirage G4', 'type' => 'Sedan'],
            ['brand' => 'Mitsubishi', 'model' => 'Strada Athlete', 'type' => 'Pickup Truck'],
            ['brand' => 'Nissan', 'model' => 'Almera', 'type' => 'Sedan'],
            ['brand' => 'Nissan', 'model' => 'Terra', 'type' => 'SUV'],
            ['brand' => 'Nissan', 'model' => 'Navara', 'type' => 'Pickup Truck'],
            ['brand' => 'Nissan', 'model' => 'Sylphy', 'type' => 'Sedan'],
            ['brand' => 'Nissan', 'model' => 'X-Trail', 'type' => 'SUV'],
            ['brand' => 'Nissan', 'model' => 'Urvan', 'type' => 'Van'],
            ['brand' => 'Nissan', 'model' => 'Sentra', 'type' => 'Sedan'],
            ['brand' => 'Nissan', 'model' => 'Frontier Navara', 'type' => 'Pickup Truck'],
            ['brand' => 'Nissan', 'model' => 'Terrano', 'type' => 'SUV'],
            ['brand' => 'Nissan', 'model' => 'Altima', 'type' => 'Sedan'],
            ['brand' => 'Nissan', 'model' => 'Maxima', 'type' => 'Sedan'],
            ['brand' => 'Nissan', 'model' => 'Leaf', 'type' => 'Hatchback'],
            ['brand' => 'Nissan', 'model' => 'GT-R', 'type' => 'Sports Car'],
            ['brand' => 'Ford', 'model' => 'Mustang', 'type' => 'Coupe'],
            ['brand' => 'Ford', 'model' => 'Ranger', 'type' => 'Pickup Truck'],
            ['brand' => 'Ford', 'model' => 'Everest', 'type' => 'SUV'],
            ['brand' => 'Ford', 'model' => 'Escape', 'type' => 'SUV'],
            ['brand' => 'Ford', 'model' => 'Expedition', 'type' => 'SUV'],
            ['brand' => 'Ford', 'model' => 'Focus', 'type' => 'Hatchback'],
            ['brand' => 'Ford', 'model' => 'Fiesta', 'type' => 'Hatchback'],
            ['brand' => 'Ford', 'model' => 'Edge', 'type' => 'SUV'],
            ['brand' => 'Ford', 'model' => 'F-150', 'type' => 'Pickup Truck'],
            ['brand' => 'Ford', 'model' => 'EcoSport', 'type' => 'SUV'],
            ['brand' => 'Ford', 'model' => 'Everest Titanium', 'type' => 'SUV'],
            ['brand' => 'Ford', 'model' => 'Ranger Raptor', 'type' => 'Pickup Truck'],
            ['brand' => 'Chevrolet', 'model' => 'Cruze', 'type' => 'Sedan'],
            ['brand' => 'Chevrolet', 'model' => 'Trailblazer', 'type' => 'SUV'],
            ['brand' => 'Chevrolet', 'model' => 'Spark', 'type' => 'Hatchback'],
            ['brand' => 'Chevrolet', 'model' => 'Malibu', 'type' => 'Sedan'],
            ['brand' => 'Chevrolet', 'model' => 'Colorado', 'type' => 'Pickup Truck'],
            ['brand' => 'Chevrolet', 'model' => 'Camaro', 'type' => 'Coupe'],
            ['brand' => 'Chevrolet', 'model' => 'Sonic', 'type' => 'Hatchback'],
            ['brand' => 'Chevrolet', 'model' => 'Captiva', 'type' => 'SUV'],
            ['brand' => 'Chevrolet', 'model' => 'Trax', 'type' => 'SUV'],
            ['brand' => 'Chevrolet', 'model' => 'Cruze LS', 'type' => 'Sedan'],
            ['brand' => 'Chevrolet', 'model' => 'Trailblazer LTX', 'type' => 'SUV'],
            ['brand' => 'Chevrolet', 'model' => 'Suburban Premier', 'type' => 'SUV'],
            ['brand' => 'Subaru', 'model' => 'Impreza', 'type' => 'Sedan'],
            ['brand' => 'Subaru', 'model' => 'Forester', 'type' => 'SUV'],
            ['brand' => 'Subaru', 'model' => 'BRZ', 'type' => 'Coupe'],
            ['brand' => 'Subaru', 'model' => 'Legacy', 'type' => 'Sedan'],
            ['brand' => 'Subaru', 'model' => 'Crosstrek', 'type' => 'SUV'],
            ['brand' => 'Subaru', 'model' => 'Outback', 'type' => 'Station Wagon'],
            ['brand' => 'Subaru', 'model' => 'Ascent', 'type' => 'SUV'],
            ['brand' => 'Subaru', 'model' => 'Levorg', 'type' => 'Station Wagon'],
            ['brand' => 'Subaru', 'model' => 'WRX', 'type' => 'Sports Car'],
            ['brand' => 'Subaru', 'model' => 'Legacy GT', 'type' => 'Sedan'],
            ['brand' => 'Subaru', 'model' => 'Forester GT Edition', 'type' => 'SUV'],
            ['brand' => 'Subaru', 'model' => 'WRX STI', 'type' => 'Sports Car'],
            // Add more car data here...
            ['brand' => 'Hyundai', 'model' => 'Accent', 'type' => 'Sedan'],
            ['brand' => 'Hyundai', 'model' => 'Tucson', 'type' => 'SUV'],
            ['brand' => 'Hyundai', 'model' => 'Grand Starex', 'type' => 'Van'],
            ['brand' => 'Hyundai', 'model' => 'Santa Fe', 'type' => 'SUV'],
            ['brand' => 'Hyundai', 'model' => 'Elantra', 'type' => 'Sedan'],
            ['brand' => 'Hyundai', 'model' => 'Sonata', 'type' => 'Sedan'],
            ['brand' => 'Hyundai', 'model' => 'Kona', 'type' => 'SUV'],
            ['brand' => 'Hyundai', 'model' => 'Tucson', 'type' => 'SUV'],
            ['brand' => 'Hyundai', 'model' => 'Venue', 'type' => 'SUV'],
            ['brand' => 'Kia', 'model' => 'Picanto', 'type' => 'Hatchback'],
            ['brand' => 'Kia', 'model' => 'Seltos', 'type' => 'SUV'],
            ['brand' => 'Kia', 'model' => 'Carnival', 'type' => 'MPV'],
            ['brand' => 'Mazda', 'model' => 'Mazda3', 'type' => 'Sedan'],
            ['brand' => 'Mazda', 'model' => 'CX-5', 'type' => 'SUV'],
            ['brand' => 'Mazda', 'model' => 'Mazda2', 'type' => 'Hatchback'],
            ['brand' => 'Suzuki', 'model' => 'Ciaz', 'type' => 'Sedan'],
            ['brand' => 'Suzuki', 'model' => 'Jimny', 'type' => 'SUV'],
            ['brand' => 'Suzuki', 'model' => 'Swift', 'type' => 'Hatchback'],
            ['brand' => 'Isuzu', 'model' => 'D-Max', 'type' => 'Pickup Truck'],
            ['brand' => 'Isuzu', 'model' => 'mu-X', 'type' => 'SUV'],
            ['brand' => 'Mercedes-Benz', 'model' => 'C-Class', 'type' => 'Sedan'],
            ['brand' => 'Mercedes-Benz', 'model' => 'GLC', 'type' => 'SUV'],
            ['brand' => 'BMW', 'model' => '3 Series', 'type' => 'Sedan'],
            ['brand' => 'BMW', 'model' => 'X5', 'type' => 'SUV'],
            ['brand' => 'Lexus', 'model' => 'ES', 'type' => 'Sedan'],
            ['brand' => 'Lexus', 'model' => 'RX', 'type' => 'SUV'],
            ['brand' => 'Audi', 'model' => 'A4', 'type' => 'Sedan'],
            ['brand' => 'Audi', 'model' => 'Q5', 'type' => 'SUV'],
            ['brand' => 'Volkswagen', 'model' => 'Jetta', 'type' => 'Sedan'],
            ['brand' => 'Volkswagen', 'model' => 'Tiguan', 'type' => 'SUV'],
            ['brand' => 'Ford', 'model' => 'Explorer', 'type' => 'SUV'],
            ['brand' => 'Ford', 'model' => 'Everest Sport', 'type' => 'SUV'],
            ['brand' => 'Chevrolet', 'model' => 'Traverse', 'type' => 'SUV'],
            ['brand' => 'Chevrolet', 'model' => 'Equinox', 'type' => 'SUV'],
            ['brand' => 'Jeep', 'model' => 'Wrangler', 'type' => 'SUV'],
            ['brand' => 'Jeep', 'model' => 'Grand Cherokee', 'type' => 'SUV'],
            ['brand' => 'Jeep', 'model' => 'Compass', 'type' => 'SUV'],
            ['brand' => 'Jeep', 'model' => 'Renegade', 'type' => 'SUV'],
            ['brand' => 'Nissan', 'model' => 'Sunny', 'type' => 'Sedan'],
            ['brand' => 'Nissan', 'model' => 'Kicks', 'type' => 'SUV'],
            ['brand' => 'Nissan', 'model' => 'Patrol Royale', 'type' => 'SUV'],
            ['brand' => 'Nissan', 'model' => '370Z', 'type' => 'Sports Car'],
            ['brand' => 'Mitsubishi', 'model' => 'Eclipse Cross', 'type' => 'SUV'],
            ['brand' => 'Mitsubishi', 'model' => 'ASX', 'type' => 'SUV'],
            ['brand' => 'Mitsubishi', 'model' => 'XPANDER CROSS', 'type' => 'MPV'],
            ['brand' => 'Mitsubishi', 'model' => 'L200', 'type' => 'Pickup Truck'],
            ['brand' => 'Honda', 'model' => 'Breeze', 'type' => 'SUV'],
            ['brand' => 'Honda', 'model' => 'Crosstar', 'type' => 'SUV'],
            ['brand' => 'Honda', 'model' => 'Legend', 'type' => 'Sedan'],
            ['brand' => 'Honda', 'model' => 'Passport', 'type' => 'SUV'],
            ['brand' => 'Honda', 'model' => 'Ridgeline', 'type' => 'Pickup Truck'],
            ['brand' => 'Honda', 'model' => 'Elysion', 'type' => 'MPV'],
            ['brand' => 'Honda', 'model' => 'S660', 'type' => 'Sports Car'],
            ['brand' => 'Hyundai', 'model' => 'Venue', 'type' => 'SUV'],
            ['brand' => 'Hyundai', 'model' => 'IONIQ 5', 'type' => 'Hatchback'],
            ['brand' => 'Hyundai', 'model' => 'IONIQ 6', 'type' => 'Sedan'],
            ['brand' => 'Hyundai', 'model' => 'IONIQ 7', 'type' => 'SUV'],
            ['brand' => 'Kia', 'model' => 'Forte', 'type' => 'Sedan'],
            ['brand' => 'Kia', 'model' => 'Ceed', 'type' => 'Hatchback'],
            ['brand' => 'Kia', 'model' => 'Stonic', 'type' => 'SUV'],
            ['brand' => 'Kia', 'model' => 'Sportage', 'type' => 'SUV'],
            ['brand' => 'Kia', 'model' => 'Sorento', 'type' => 'SUV'],
            ['brand' => 'Kia', 'model' => 'Telluride', 'type' => 'SUV'],
            ['brand' => 'Mazda', 'model' => 'MX-30', 'type' => 'SUV'],
            ['brand' => 'Mazda', 'model' => 'CX-30', 'type' => 'SUV'],
            ['brand' => 'Mazda', 'model' => 'CX-9', 'type' => 'SUV'],
            ['brand' => 'Mazda', 'model' => 'MX-5 Miata', 'type' => 'Sports Car'],
            ['brand' => 'Mercedes-Benz', 'model' => 'E-Class', 'type' => 'Sedan'],
            ['brand' => 'Mercedes-Benz', 'model' => 'S-Class', 'type' => 'Sedan'],
            ['brand' => 'Mercedes-Benz', 'model' => 'G-Class', 'type' => 'SUV'],
            ['brand' => 'Mercedes-Benz', 'model' => 'GLE', 'type' => 'SUV'],
            ['brand' => 'Mercedes-Benz', 'model' => 'GLS', 'type' => 'SUV'],
            ['brand' => 'Mercedes-Benz', 'model' => 'EQC', 'type' => 'SUV'],
            ['brand' => 'BMW', 'model' => '5 Series', 'type' => 'Sedan'],
            ['brand' => 'BMW', 'model' => '7 Series', 'type' => 'Sedan'],
            ['brand' => 'BMW', 'model' => 'X1', 'type' => 'SUV'],
            ['brand' => 'BMW', 'model' => 'X3', 'type' => 'SUV'],
            ['brand' => 'BMW', 'model' => 'X4', 'type' => 'SUV'],
            ['brand' => 'BMW', 'model' => 'X6', 'type' => 'SUV'],
            ['brand' => 'BMW', 'model' => 'i3', 'type' => 'Hatchback'],
            ['brand' => 'BMW', 'model' => 'i4', 'type' => 'Sedan'],
            ['brand' => 'BMW', 'model' => 'iX3', 'type' => 'SUV'],
            ['brand' => 'BMW', 'model' => 'iX', 'type' => 'SUV'],
            ['brand' => 'Audi', 'model' => 'A3', 'type' => 'Sedan'],
            ['brand' => 'Audi', 'model' => 'A6', 'type' => 'Sedan'],
            ['brand' => 'Audi', 'model' => 'A7', 'type' => 'Sedan'],
            ['brand' => 'Audi', 'model' => 'A8', 'type' => 'Sedan'],
            ['brand' => 'Audi', 'model' => 'Q3', 'type' => 'SUV'],
            ['brand' => 'Audi', 'model' => 'Q7', 'type' => 'SUV'],
            ['brand' => 'Audi', 'model' => 'Q8', 'type' => 'SUV'],
            ['brand' => 'Audi', 'model' => 'e-tron', 'type' => 'SUV'],
            ['brand' => 'Volkswagen', 'model' => 'Passat', 'type' => 'Sedan'],
            ['brand' => 'Volkswagen', 'model' => 'Arteon', 'type' => 'Sedan'],
            ['brand' => 'Volkswagen', 'model' => 'Golf', 'type' => 'Hatchback'],
            ['brand' => 'Volkswagen', 'model' => 'ID.3', 'type' => 'Hatchback'],
            ['brand' => 'Volkswagen', 'model' => 'ID.4', 'type' => 'SUV'],
            ['brand' => 'Volkswagen', 'model' => 'Touareg', 'type' => 'SUV'],
            ['brand' => 'Volkswagen', 'model' => 'T-Cross', 'type' => 'SUV'],
            ['brand' => 'Volkswagen', 'model' => 'T-Roc', 'type' => 'SUV'],
            ['brand' => 'Volkswagen', 'model' => 'Atlas', 'type' => 'SUV'],
            ['brand' => 'Volkswagen', 'model' => 'Amarok', 'type' => 'Pickup Truck'],
            ['brand' => 'Ford', 'model' => 'Fiesta', 'type' => 'Hatchback'],
            ['brand' => 'Ford', 'model' => 'Focus', 'type' => 'Hatchback'],
            ['brand' => 'Ford', 'model' => 'Mustang', 'type' => 'Sports Car'],
            ['brand' => 'Ford', 'model' => 'Edge', 'type' => 'SUV'],
            ['brand' => 'Ford', 'model' => 'Ranger', 'type' => 'Pickup Truck'],
            ['brand' => 'Chevrolet', 'model' => 'Malibu', 'type' => 'Sedan'],
            ['brand' => 'Chevrolet', 'model' => 'Trailblazer', 'type' => 'SUV'],
            ['brand' => 'Chevrolet', 'model' => 'Tahoe', 'type' => 'SUV'],
            ['brand' => 'Chevrolet', 'model' => 'Corvette', 'type' => 'Sports Car'],
            ['brand' => 'Jeep', 'model' => 'Gladiator', 'type' => 'Pickup Truck'],
            ['brand' => 'Jeep', 'model' => 'Cherokee', 'type' => 'SUV'],
            ['brand' => 'Jeep', 'model' => 'Trackhawk', 'type' => 'SUV'],
            ['brand' => 'Jeep', 'model' => 'Commander', 'type' => 'SUV'],
            ['brand' => 'Jeep', 'model' => 'Wagoneer', 'type' => 'SUV'],
        ];

        DB::table('car_data')->insert($carData);
    }
}
